### ISSUE TITLE
I can not download the driver.

### ISSUE THREAD

**Issue by shadesoma** [InfinityGhost/OpenTabletDriver.Installer#4]
Hey. I am from Russia and when I try to download a driver the download speed is very slow. And then it completely stops downloading. The problem is not on my side, everything else downloads well. Perhaps because the Amazon s3 is far away.

**Comment by Mrcubix** [comment]
the problem isn't on our side either, you should try to contact github instead, Closed.

**Comment by shadesoma** [comment]
Thank you so much. Downloaded
