### ISSUE TITLE
can't move in an admin window

### ISSUE THREAD

**Issue by wisnc** [InfinityGhost/OpenTabletDriver.Installer#41]
Windows Version: windows 10

Tablet Driver version: 0.5.3.2

Tablet model: veikk s640

everything worked perfectly before, during that time i was using the official veikk drivers, but then i feel like the settings are lacking so i uninstalled the veikk drivers and installed the hawku drivers as it was the first one on a google search. it won't work as it tells me that the vmulti device wont work or something, so i went back to veikk drivers and it kinda messed up something that now whenever an administrator enabled window is on top the tablet won't move the mouse. Then i searched for helped on hawku issues and saw that it was already abandoned so i moved here and maybe opentabletdriver will help me fix this issue

**Comment by X9VoiD** [comment]
Sending input to elevated processes is blocked by Windows. This is impossible to fix from OTD's side. If you really insist on such feature then use VMultiMode plugin.

**Comment by wisnc** [comment]
when i was using the original official driver of my tablet, it used to work on any processes including elevated processes. but now ever since i installed other open sourced drivers it stopped doing that, even reverting back wont work. thanks for the suggestion i will look on it.
