### ISSUE TITLE
Asks to install a newer version of .NET Runtime, but neither version will allow me to proceed with installation of OpenDriver

### ISSUE THREAD

**Issue by LupusHacker** [InfinityGhost/OpenTabletDriver.Installer#43]
Neither Console (64/86) nor Desktop (64/86) work. It would help if the installation instructions were more specific on which version to look for.

**Comment by InfinityGhost** [comment]
This cannot be changed, it is built into the .NET library.

**Comment by InfinityGhost** [comment]
However, the correct version can be grabbed from [here](http://opentabletdriver.net/framework)
